### ISSUE TITLE
No line is shown when chart data is all 0's

### ISSUE THREAD

**Issue by guyzk** [aeyrium/bezier-chart#15]
When all chart data values are 0, no line is rendered and an exception is thrown.
Added the logs

```DART
09:30:20.568 7 info flutter.tools I/flutter ( 4676): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
09:30:20.568 8 info flutter.tools I/flutter ( 4676): The following assertion was thrown during paint():
09:30:20.568 9 info flutter.tools I/flutter ( 4676): Offset argument contained a NaN value.
09:30:20.569 10 info flutter.tools I/flutter ( 4676): 'dart:ui/painting.dart':
09:30:20.569 11 info flutter.tools I/flutter ( 4676): Failed assertion: line 38: '<optimized out>'
09:30:20.569 12 info flutter.tools I/flutter ( 4676): 
09:30:20.569 13 info flutter.tools I/flutter ( 4676): Either the assertion indicates an error in the framework itself, or we should provide substantially
09:30:20.569 14 info flutter.tools I/flutter ( 4676): more information in this error message to help you determine and fix the underlying cause.
09:30:20.569 15 info flutter.tools I/flutter ( 4676): In either case, please report this assertion by filing a bug on GitHub:
09:30:20.569 16 info flutter.tools I/flutter ( 4676):   https://github.com/flutter/flutter/issues/new?template=BUG.md
09:30:20.569 17 info flutter.tools I/flutter ( 4676): 
09:30:20.569 18 info flutter.tools I/flutter ( 4676): When the exception was thrown, this was the stack:
09:30:20.569 19 info flutter.tools I/flutter ( 4676): #2      _offsetIsValid (dart:ui/painting.dart:38:10)
09:30:20.569 20 info flutter.tools I/flutter ( 4676): #3      _encodePointList (dart:ui/painting.dart:2672:12)
09:30:20.569 21 info flutter.tools I/flutter ( 4676): #4      Canvas.drawPoints (dart:ui/painting.dart:3587:63)
09:30:20.569 22 info flutter.tools I/flutter ( 4676): #5      _BezierChartPainter.paint._drawBezierLinePath (package:bezier_chart/src/bezier_chart_widget.dart:1078:16)
09:30:20.569 23 info flutter.tools I/flutter ( 4676): #6      _BezierChartPainter.paint (package:bezier_chart/src/bezier_chart_widget.dart:1098:26)
09:30:20.569 24 info flutter.tools I/flutter ( 4676): #7      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
09:30:20.569 25 info flutter.tools I/flutter ( 4676): #8      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
09:30:20.569 26 info flutter.tools I/flutter ( 4676): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
09:30:20.569 27 info flutter.tools I/flutter ( 4676): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
09:30:20.569 28 info flutter.tools I/flutter ( 4676): #11     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
09:30:20.569 29 info flutter.tools I/flutter ( 4676): #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
09:30:20.569 30 info flutter.tools I/flutter ( 4676): #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
09:30:20.569 31 info flutter.tools I/flutter ( 4676): #14     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
09:30:20.569 32 info flutter.tools I/flutter ( 4676): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
09:30:20.569 33 info flutter.tools I/flutter ( 4676): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
09:30:20.569 34 info flutter.tools I/flutter ( 4676): #17     _RenderSingleChildViewport.paint.paintContents (package:bezier_chart/src/my_single_child_scroll_view.dart:338:17)
09:30:20.569 35 info flutter.tools I/flutter ( 4676): #18     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:369:12)
09:30:20.569 36 info flutter.tools I/flutter ( 4676): #19     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:393:7)
09:30:20.569 37 info flutter.tools I/flutter ( 4676): #20     _RenderSingleChildViewport.paint (package:bezier_chart/src/my_single_child_scroll_view.dart:344:17)
09:30:20.569 38 info flutter.tools I/flutter ( 4676): #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
09:30:20.569 39 info flutter.tools I/flutter ( 4676): #22     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:127:11)
09:30:20.569 40 info flutter.tools I/flutter ( 4676): #23     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
09:30:20.569 41 info flutter.tools I/flutter ( 4676): #24     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:858:29)
09:30:20.569 42 info flutter.tools I/flutter ( 4676): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348:19)
09:30:20.569 43 info flutter.tools I/flutter ( 4676): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
09:30:20.569 44 info flutter.tools I/flutter ( 4676): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
09:30:20.569 45 info flutter.tools I/flutter ( 4676): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
09:30:20.569 46 info flutter.tools I/flutter ( 4676): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
09:30:20.569 47 info flutter.tools I/flutter ( 4676): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
09:30:20.570 48 info flutter.tools I/flutter ( 4676): #32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
09:30:20.570 49 info flutter.tools I/flutter ( 4676): #33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
09:30:20.570 50 info flutter.tools I/flutter ( 4676): #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
09:30:20.570 51 info flutter.tools I/flutter ( 4676): (elided 3 frames from class _AssertionError and package dart:async-patch)
09:30:20.570 52 info flutter.tools I/flutter ( 4676): 
09:30:20.570 53 info flutter.tools I/flutter ( 4676): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#db479 relayoutBoundary=up18:
09:30:20.570 54 info flutter.tools I/flutter ( 4676):   creator: CustomPaint ← Align ← Padding ← _SingleChildViewport ← IgnorePointer-[GlobalKey#f9c54] ←
09:30:20.570 55 info flutter.tools I/flutter ( 4676):     Semantics ← Listener ← _GestureSemantics ←
09:30:20.570 56 info flutter.tools I/flutter ( 4676):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#570bb] ← Listener ← _ScrollableScope
09:30:20.570 57 info flutter.tools I/flutter ( 4676):     ← _ScrollSemantics-[GlobalKey#db183] ← ⋯
09:30:20.570 58 info flutter.tools I/flutter ( 4676):   parentData: offset=Offset(0.0, 48.3) (can use size)
09:30:20.570 59 info flutter.tools I/flutter ( 4676):   constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=284.0)
09:30:20.570 60 info flutter.tools I/flutter ( 4676):   size: Size(1166.2, 227.2)
09:30:20.570 61 info flutter.tools I/flutter ( 4676): This RenderObject has no descendants.

```

**Comment by diegoveloper** [comment]
Could you add the code to reproduce the issue?

**Comment by guyzk** [comment]
This started after the latest update to the package
You can use the code snippet from git but with 0 values to repro.
Please fix as this is a totally valid and common scenario

```DART
BezierChart(
        fromDate: fromDate,
        bezierChartScale: BezierChartScale.WEEKLY,
        toDate: toDate,
        selectedDate: toDate,
        series: [
          BezierLine(
            label: "Duty",
            onMissingValue: (dateTime) {
              return 0.0;
            },
            data: [
              DataPoint<DateTime>(value: 0, xAxis: date1),
              DataPoint<DateTime>(value: 0, xAxis: date2),
              DataPoint<DateTime>(value: 0, xAxis: date3),
              DataPoint<DateTime>(value: 0, xAxis: date4),
              DataPoint<DateTime>(value: 0, xAxis: date5),
              DataPoint<DateTime>(value: 0, xAxis: date6),
              DataPoint<DateTime>(value: 0, xAxis: date7),
            ],
          ),
        ],
        config: BezierChartConfig(
          verticalIndicatorStrokeWidth: 3.0,
          verticalIndicatorColor: Colors.black26,
          showVerticalIndicator: true,
          verticalIndicatorFixedPosition: false,
          backgroundColor: Colors.red,
          footerHeight: 30.0,
        ),
      )
```

**Comment by diegoveloper** [comment]
Fixed,  I updated the code, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Let me knows if it works.

**Comment by guyzk** [comment]
Fixed. Thanks!
